AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 NGINX website for deployment via CodePipeline, with public IP

Parameters:
  VPCID:
    Type: String
    Default: vpc-0538171a960b3eb0f
    Description: VPC ID where the instance will launch

  SubnetID:
    Type: String
    Default: subnet-0a7427cd2ca79b644
    Description: Subnet ID for the EC2 instance

Resources:
  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: DevMachine  # Ensure this key exists or pass it as a parameter
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 in us-east-1
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref SubnetID
          GroupSet:
            - !Ref WebServerSG
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras enable nginx1
          yum install -y nginx
          systemctl start nginx
          systemctl enable nginx
          echo "<h1>Deployed with CodePipeline + CloudFormation!</h1>" > /usr/share/nginx/html/index.html

Outputs:
  WebsiteURL:
    Description: Public URL for the NGINX website
    Value: !Sub "http://${WebServerInstance.PublicDnsName}"
