AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 NGINX website

Parameters:
  KeyName:
    Description: Name of existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref WebServerSG
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 in us-east-1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras enable nginx1
          yum install -y nginx
          systemctl start nginx
          systemctl enable nginx
          echo "<h1>Deployed with CloudFormation + CodePipeline!</h1>" > /usr/share/nginx/html/index.html

Outputs:
  WebsiteURL:
    Description: Public URL
    Value: !Sub "http://${WebServerInstance.PublicDnsName}"
